### ISSUE TITLE
"Deprecation warning" message using ansible v2.0.1

### ISSUE THREAD

**Issue by franlr** [GROG/ansible-role-user#3]
Hi,
I've tested your role using a CentOS 6.7 + ansible 2.0.1 environment. Everything is fine but I've seen this deprecation warning message:

> [DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{user_list}}'). This feature will be removed in a
> future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
> [DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{user_list_host}}'). This feature will be removed in
> a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
> [DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{user_list_group}}'). This feature will be removed in
>  a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

Are you thinking to adapt the syntax for ansible 2.x?
Thanx!

**Comment by groggemans** [comment]
It's been on my todo list for a while. I'll try to make some time to have a look at it this week!

**Comment by groggemans** [comment]
Fixed #4
